version: "3.8"

services:
  social_network:
    build:
    context: .
    dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - database
    networks:
      - default
    ports:
      - "8080:8080"

database:
  image: postgres:alpine
  restart: always
  env_file:
    - POSTGRES_NAME=${DB_NAME}
    - POSTGRES_USER=${DB_USER}
    - POSTGRES_PORT=${DB_PORT}
    - POSTGRES_PASSWORD=${DB_PASSWORD}
    - POSTGRES_HOST=$[DB_HOST}
  ports:
    - "5432:5432"
  volumes:
    - data: /postgresql/data

volumes:
  data:


