version: '2.15'

services:

  #

  memcached:
    restart: on-failure
    image: memcached

  #
  redis:
    image: redis:latest

    restart: on-failure

    hostname: redis

    command: redis-server --port 6379 --requirepass password

    ports:
      - "6379:6379"

  #

  postgres:
    image: postgres:latest

    restart: on-failure

    command: -p 5431

    ports:
      - "5431:5431"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  #

  server:
    restart: on-failure
    build: .
    container_name: 'social-network'
    ports:
      - "3000:3000"
  
    depends_on:
      - postgres
      - redis
      - memcached

    environment:
      ARGS: -env

      #Postgres
      POSTGRES_PORT: ${DB_PORT}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

      POSTGRES_DB: ${DB_NAME}
      POSTGRES_HOST: ${DB_HOST}

      # Redis 
      REDIS_HOST: ${REDIS_DSN}
      REDIS_PASS: ${REDIS_PASSWORD}

      #Memcached

      MEMCACHED_HOST: ${MEMCACHED_DSN}

networks:
  hosts:
    driver: "host"
