version: "3.9"
services:
  social_network:
    build: 
     context: .
     dockerfile: Dockerfile
    ports:
      - "8000:8080"
    depends_on:
      - database
    env_file: .env
    container_name: social_network

  database:
    image: postgres:latest
    restart: always 
    environment:
      - POSTGRES_NAME=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PORT=${DB_PORT}
      - POSTGRES_PASSWORD=${DB_PASSWORD:? database password not set}
      - POSTGRES_HOST=${DB_HOST}
    ports:
      - "5432:5432"
    command: social-network --insecure