version: "3.8"

services:
  social_network:
    build:
    context: .
    dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - database
    networks:
      - default
    ports:
      - "8080:8080"

database:
  image: postgres:alpine
  restart: always
  env_file:
    - .env
  ports:
    - "5432:5432"
  volumes:
    - data: /postgresql/data

volumes:
  data:


